import { mutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * Seed the database with sample artifacts for testing the artifact identification game
 */
export const seedArtifacts = mutation({
  args: {},
  returns: v.array(v.id("gameArtifacts")),
  handler: async (ctx, args) => {
    // Check if artifacts already exist
    const existingArtifacts = await ctx.db.query("gameArtifacts").collect();
    if (existingArtifacts.length > 0) {
      console.log("Artifacts already exist, skipping seed");
      return existingArtifacts.map((a) => a._id);
    }

    const sampleArtifacts = [
      {
        name: "Ancient Greek Amphora",
        description:
          "A large ceramic vessel used for storing wine and oil in ancient Greece",
        historicalPeriod: "Classical Antiquity",
        culture: "Ancient Greek",
        dateRange: "500-300 BCE",
        significance:
          "Essential for understanding ancient Greek trade and daily life",
        imageUrl:
          "https://placehold.co/400x400/1e3a8a/fbbf24?text=Greek+Amphora+🏺",
        discoveryLocation: "Mediterranean Sea, off the coast of Cyprus",
        conservationNotes:
          "Well-preserved due to underwater conditions, minimal restoration needed",
        difficulty: "beginner" as const,
        category: "Pottery",
        isActive: true,
      },
      {
        name: "Roman Bronze Coin",
        description: "A bronze sestertius from the reign of Emperor Trajan",
        historicalPeriod: "Roman Empire",
        culture: "Roman",
        dateRange: "98-117 CE",
        significance:
          "Provides insight into Roman monetary system and imperial propaganda",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Adriatic Sea, near ancient Roman port",
        conservationNotes:
          "Significant corrosion, requires careful cleaning and stabilization",
        difficulty: "intermediate" as const,
        category: "Currency",
        isActive: true,
      },
      {
        name: "Viking Iron Sword",
        description:
          "A well-preserved iron sword with intricate hilt decorations",
        historicalPeriod: "Viking Age",
        culture: "Norse",
        dateRange: "800-1000 CE",
        significance: "Demonstrates Viking craftsmanship and warrior culture",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Baltic Sea, near Swedish coastline",
        conservationNotes:
          "Excellent preservation in cold water, original leather grip remains",
        difficulty: "advanced" as const,
        category: "Weapons",
        isActive: true,
      },
      {
        name: "Phoenician Glass Vessel",
        description: "A delicate glass perfume bottle with iridescent patina",
        historicalPeriod: "Iron Age",
        culture: "Phoenician",
        dateRange: "800-500 BCE",
        significance: "Shows early glass-making techniques and trade networks",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Eastern Mediterranean, off Lebanese coast",
        conservationNotes:
          "Fragile condition, requires specialized handling and display",
        difficulty: "intermediate" as const,
        category: "Glass",
        isActive: true,
      },
      {
        name: "Egyptian Canopic Jar",
        description:
          "A limestone jar used for storing organs during mummification",
        historicalPeriod: "New Kingdom",
        culture: "Ancient Egyptian",
        dateRange: "1550-1077 BCE",
        significance:
          "Reveals ancient Egyptian burial practices and religious beliefs",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Red Sea, near ancient Egyptian port",
        conservationNotes:
          "Stone material well-preserved, hieroglyphic inscriptions intact",
        difficulty: "beginner" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Medieval Ship's Anchor",
        description: "A large iron anchor from a medieval merchant vessel",
        historicalPeriod: "Medieval",
        culture: "European",
        dateRange: "1200-1400 CE",
        significance:
          "Demonstrates medieval shipbuilding and maritime technology",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "North Sea, off English coast",
        conservationNotes: "Heavy corrosion, requires electrolytic treatment",
        difficulty: "advanced" as const,
        category: "Maritime",
        isActive: true,
      },
      {
        name: "Mayan Jade Ornament",
        description: "An intricately carved jade pendant with Mayan glyphs",
        historicalPeriod: "Classic Maya",
        culture: "Mayan",
        dateRange: "250-900 CE",
        significance: "Shows Mayan artistic skill and religious symbolism",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Caribbean Sea, off Yucatan Peninsula",
        conservationNotes:
          "Excellent condition, jade naturally resistant to water damage",
        difficulty: "advanced" as const,
        category: "Jewelry",
        isActive: true,
      },
      {
        name: "Chinese Porcelain Bowl",
        description: "A blue and white porcelain bowl from the Ming Dynasty",
        historicalPeriod: "Ming Dynasty",
        culture: "Chinese",
        dateRange: "1368-1644 CE",
        significance: "Represents Chinese ceramic artistry and trade expansion",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "South China Sea, ancient trade route",
        conservationNotes: "Minor chips and cracks, glaze mostly intact",
        difficulty: "intermediate" as const,
        category: "Pottery",
        isActive: true,
      },
      {
        name: "Aztec Stone Calendar",
        description: "A carved stone disc depicting the Aztec calendar system",
        historicalPeriod: "Postclassic Mesoamerica",
        culture: "Aztec",
        dateRange: "1400-1521 CE",
        significance:
          "Demonstrates advanced Aztec astronomy and timekeeping knowledge",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Gulf of Mexico, near ancient Aztec port",
        conservationNotes: "Stone well-preserved, intricate carvings intact",
        difficulty: "advanced" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Persian Silver Dagger",
        description: "An ornate silver dagger with gemstone inlays",
        historicalPeriod: "Achaemenid Empire",
        culture: "Persian",
        dateRange: "550-330 BCE",
        significance:
          "Shows Persian metalworking excellence and royal craftsmanship",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Persian Gulf, ancient trade route",
        conservationNotes: "Silver tarnished but gemstones intact",
        difficulty: "advanced" as const,
        category: "Weapons",
        isActive: true,
      },
      {
        name: "Celtic Bronze Torc",
        description: "A twisted bronze neck ring worn by Celtic nobility",
        historicalPeriod: "Iron Age",
        culture: "Celtic",
        dateRange: "300-100 BCE",
        significance:
          "Indicates Celtic social hierarchy and metalworking skills",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Irish Sea, near ancient Celtic settlement",
        conservationNotes: "Bronze patina stable, minimal corrosion",
        difficulty: "intermediate" as const,
        category: "Jewelry",
        isActive: true,
      },
      {
        name: "Japanese Samurai Helmet",
        description: "An iron kabuto helmet with decorative crest",
        historicalPeriod: "Edo Period",
        culture: "Japanese",
        dateRange: "1603-1868 CE",
        significance:
          "Represents samurai warrior culture and armor craftsmanship",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Sea of Japan, shipwreck site",
        conservationNotes: "Iron corroded, lacquer work partially preserved",
        difficulty: "advanced" as const,
        category: "Armor",
        isActive: true,
      },
      {
        name: "Mesopotamian Clay Tablet",
        description: "A cuneiform tablet recording ancient trade transactions",
        historicalPeriod: "Bronze Age",
        culture: "Mesopotamian",
        dateRange: "2000-1500 BCE",
        significance: "Provides evidence of early writing and commerce",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Persian Gulf, ancient Sumerian port",
        conservationNotes: "Clay hardened by water, cuneiform legible",
        difficulty: "beginner" as const,
        category: "Writing",
        isActive: true,
      },
      {
        name: "Byzantine Gold Cross",
        description: "An ornate gold cross with enamel decoration",
        historicalPeriod: "Byzantine Empire",
        culture: "Byzantine",
        dateRange: "500-1000 CE",
        significance: "Shows Byzantine religious art and goldsmithing",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Aegean Sea, near Constantinople",
        conservationNotes: "Gold unaffected by water, enamel intact",
        difficulty: "intermediate" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Polynesian Stone Adze",
        description: "A basalt stone tool used for woodworking",
        historicalPeriod: "Polynesian Settlement",
        culture: "Polynesian",
        dateRange: "1000-1500 CE",
        significance:
          "Demonstrates Polynesian tool-making and navigation culture",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Pacific Ocean, near Hawaiian Islands",
        conservationNotes: "Stone naturally preserved, binding materials lost",
        difficulty: "beginner" as const,
        category: "Tools",
        isActive: true,
      },
      {
        name: "Inca Silver Llama Figurine",
        description: "A small silver llama statue used in religious ceremonies",
        historicalPeriod: "Inca Empire",
        culture: "Inca",
        dateRange: "1400-1533 CE",
        significance: "Reveals Inca religious practices and metalworking",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Pacific Ocean, off Peruvian coast",
        conservationNotes: "Silver tarnished but form intact",
        difficulty: "intermediate" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Etruscan Bronze Mirror",
        description:
          "A polished bronze mirror with engraved mythological scenes",
        historicalPeriod: "Etruscan Civilization",
        culture: "Etruscan",
        dateRange: "700-400 BCE",
        significance: "Shows Etruscan art and daily life practices",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Tyrrhenian Sea, off Italian coast",
        conservationNotes: "Bronze patina, engravings still visible",
        difficulty: "advanced" as const,
        category: "Household",
        isActive: true,
      },
      {
        name: "Minoan Bull Rhyton",
        description:
          "A ceramic vessel shaped like a bull's head for ritual use",
        historicalPeriod: "Minoan Civilization",
        culture: "Minoan",
        dateRange: "1700-1450 BCE",
        significance: "Demonstrates Minoan religious practices and ceramic art",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Aegean Sea, near Crete",
        conservationNotes: "Ceramic intact, original paint traces visible",
        difficulty: "intermediate" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Anglo-Saxon Gold Brooch",
        description: "An intricate gold brooch with garnet inlays",
        historicalPeriod: "Early Medieval",
        culture: "Anglo-Saxon",
        dateRange: "600-800 CE",
        significance:
          "Shows Anglo-Saxon jewelry craftsmanship and status symbols",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "North Sea, near English coast",
        conservationNotes: "Gold preserved, some garnets missing",
        difficulty: "advanced" as const,
        category: "Jewelry",
        isActive: true,
      },
      {
        name: "Carthaginian Trade Amphora",
        description: "A large ceramic jar used for transporting olive oil",
        historicalPeriod: "Punic Period",
        culture: "Carthaginian",
        dateRange: "500-200 BCE",
        significance: "Evidence of Carthaginian maritime trade networks",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Mediterranean Sea, ancient trade route",
        conservationNotes: "Ceramic well-preserved, merchant marks visible",
        difficulty: "beginner" as const,
        category: "Pottery",
        isActive: true,
      },
      {
        name: "Olmec Jade Mask",
        description: "A ceremonial jade mask with distinctive Olmec features",
        historicalPeriod: "Preclassic Mesoamerica",
        culture: "Olmec",
        dateRange: "1200-400 BCE",
        significance:
          "Represents early Mesoamerican civilization and jade working",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Gulf of Mexico, near Olmec heartland",
        conservationNotes: "Jade naturally preserved, no restoration needed",
        difficulty: "advanced" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Scythian Gold Comb",
        description: "An ornate gold comb depicting warriors in battle",
        historicalPeriod: "Iron Age",
        culture: "Scythian",
        dateRange: "400-300 BCE",
        significance: "Shows Scythian goldsmithing and warrior culture",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Black Sea, ancient Scythian territory",
        conservationNotes: "Gold perfectly preserved, intricate details intact",
        difficulty: "advanced" as const,
        category: "Jewelry",
        isActive: true,
      },
      {
        name: "Nabataean Pottery Lamp",
        description: "A terracotta oil lamp with geometric decorations",
        historicalPeriod: "Hellenistic Period",
        culture: "Nabataean",
        dateRange: "100 BCE-100 CE",
        significance: "Demonstrates Nabataean pottery and daily life",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Red Sea, ancient trade route",
        conservationNotes: "Terracotta intact, soot marks from use visible",
        difficulty: "beginner" as const,
        category: "Household",
        isActive: true,
      },
      {
        name: "Khmer Bronze Buddha",
        description: "A bronze Buddha statue in meditation pose",
        historicalPeriod: "Angkor Period",
        culture: "Khmer",
        dateRange: "900-1200 CE",
        significance: "Represents Khmer Buddhist art and religious practices",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Gulf of Thailand, ancient port",
        conservationNotes: "Bronze patina stable, serene expression preserved",
        difficulty: "intermediate" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Phoenician Ivory Plaque",
        description: "An intricately carved ivory panel with Egyptian motifs",
        historicalPeriod: "Iron Age",
        culture: "Phoenician",
        dateRange: "900-700 BCE",
        significance:
          "Shows Phoenician artistic synthesis and trade connections",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Mediterranean Sea, off Lebanese coast",
        conservationNotes: "Ivory preserved in water, carvings detailed",
        difficulty: "advanced" as const,
        category: "Art",
        isActive: true,
      },
      {
        name: "Mycenaean Gold Death Mask",
        description: "A hammered gold funeral mask from a royal tomb",
        historicalPeriod: "Late Bronze Age",
        culture: "Mycenaean",
        dateRange: "1600-1500 BCE",
        significance: "Reveals Mycenaean burial customs and goldworking",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Aegean Sea, near Mycenae",
        conservationNotes: "Gold unaffected by water, facial features clear",
        difficulty: "advanced" as const,
        category: "Religious",
        isActive: true,
      },
      {
        name: "Hittite Iron Spearhead",
        description: "An iron spearhead showing early iron-working technology",
        historicalPeriod: "Late Bronze Age",
        culture: "Hittite",
        dateRange: "1400-1200 BCE",
        significance: "Evidence of early iron metallurgy in ancient Near East",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Eastern Mediterranean, ancient Hittite region",
        conservationNotes: "Heavy iron corrosion, requires stabilization",
        difficulty: "intermediate" as const,
        category: "Weapons",
        isActive: true,
      },
      {
        name: "Nubian Gold Earring",
        description: "An elaborate gold earring with granulation technique",
        historicalPeriod: "Kingdom of Kush",
        culture: "Nubian",
        dateRange: "800-300 BCE",
        significance: "Shows Nubian goldsmithing excellence and trade wealth",
        imageUrl: "/images/Gemini_Generated_Image_rzojr4rzojr4rzoj.png",
        discoveryLocation: "Red Sea, ancient Nubian trade route",
        conservationNotes: "Gold preserved, granulation work intact",
        difficulty: "intermediate" as const,
        category: "Jewelry",
        isActive: true,
      },
    ];

    const artifactIds = [];
    for (const artifact of sampleArtifacts) {
      const id = await ctx.db.insert("gameArtifacts", artifact);
      artifactIds.push(id);
    }

    console.log(`Created ${artifactIds.length} sample artifacts`);
    return artifactIds;
  },
});
